### ISSUE TITLE
switch to mdast?

### ISSUE THREAD

**Issue by yoshuawuyts** [yoshuawuyts/mdjson#3]
https://github.com/wooorm/mdast

`mdast` has a bunch of plugins that could be loaded in to make the output render better.

**Comment by wooorm** [comment]
:+1:

Look into using [**mdast-range**](https://github.com/wooorm/mdast-range) to get index-based positional information on each node, based on the given file, and use that extract raw markdown content from [`file#toString()`](https://github.com/wooorm/mdast/blob/master/doc/mdast.3.md#filetostring)

**Comment by yoshuawuyts** [comment]
Closed in 1ea53cf.
